Need to include numpy directory in order to access numpy functions in C
Was getting this error:

src/integrator.c:687:10: fatal error: 'numpy/arrayobject.h' file not found
#include "numpy/arrayobject.h"
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.

This edit fixed it.